### PR TITLE
VideoPlayer and Pseudo Streaming

### PR DESCRIPTION
**Pull request by pol2095**
I implemented Pseudo Streaming like [JW Player](http://support.jwplayer.com/customer/portal/articles/1430518-pseudo-streaming-in-flash)

``` as3
var player:VideoPlayer = new VideoPlayer();
player.move(50, 20);
player.setSize(300, 300);

var controls:LayoutGroup = new LayoutGroup();
controls.styleNameList.add(LayoutGroup.ALTERNATE_STYLE_NAME_TOOLBAR);

var controlsLayoutData:AnchorLayoutData = new AnchorLayoutData();
controlsLayoutData.left = 0;
controlsLayoutData.right = 0;
controlsLayoutData.bottom = 0;
controls.layoutData = controlsLayoutData;

var playPauseButton:PlayPauseToggleButton = new PlayPauseToggleButton();
controls.addChild(playPauseButton);

var seekBar:SeekSlider = new SeekSlider();
seekBar.layoutData = new HorizontalLayoutData(100, 100);
controls.addChild(seekBar);

var muteButton:MuteToggleButton = new MuteToggleButton();
controls.addChild(muteButton);

var fullScreenButton:FullScreenToggleButton = new FullScreenToggleButton();
controls.addChild(fullScreenButton);

player.addChild(controls);

var view:ImageLoader = new ImageLoader();
var viewLayoutData:AnchorLayoutData = new AnchorLayoutData(0, 0, 0, 0);
viewLayoutData.bottomAnchorDisplayObject = controls;
view.layoutData = viewLayoutData;
player.addChild(view);

player.width = 3 * this.stage.stageWidth / 4;
this.addChild(player);

player.addEventListener(Event.READY, function(event:Event):void
{
    view.source = player.texture;
});

player.pseudoStreaming = true;
player.videoSource = "http://www.site.com/video.mp4";
```

### CODE REVIEW

**Comment by zenrobin** [comment]
I've been searching for a way to advance "streamed" video frame by frame, or to a very specific time (1/30th of a sec, 2/30 of a sec, etc). 

Any chance this streaming pull request offers this level of control?

**Comment by joshtynjala** [comment]
Thanks for the pull request. I'll try to support this feature when I get a chance. Your modifications require some tweaks, so I can't simply merge them as-is

For instance, your modifications to SeekSlider are not compatible with SoundPlayer. You've made the assumption that SeekSlider will only be used with VideoPlayer, and that will result in a runtime error when the _videoPlayer variable is null. To be honest, I think these specific modifications should probably be put directly into VideoPlayer rather than SeekSlider, because the slider shouldn't care about what type of media is playing. It should be possible for the VideoPlayer to handle all of this, I think.

There are some other tweaks needed too. There should be a property that allows the "start" query parameter to be customized. The reference to the "NetStream.Play.Start" string should be a constant like the others. Any public properties added should be getters and setters so that they may be overridden, and of course, they need to be documented.

For my own future reference, the [Pseudo Streaming in Flash](http://support.jwplayer.com/customer/portal/articles/1430518-pseudo-streaming-in-flash) article by JW Player looks like it has useful information on this topic.

**Comment by pol2095** [comment]
@joshtynjala
Good, if you need any help let me know

@zenrobin
I add a property "start" that allows to advance "streamed" video to a specific time
```as3
var player:VideoPlayer = new VideoPlayer();
player.move(50, 20);
player.setSize(300, 300);
 
var controls:LayoutGroup = new LayoutGroup();
controls.styleNameList.add(LayoutGroup.ALTERNATE_STYLE_NAME_TOOLBAR);
 
var controlsLayoutData:AnchorLayoutData = new AnchorLayoutData();
controlsLayoutData.left = 0;
controlsLayoutData.right = 0;
controlsLayoutData.bottom = 0;
controls.layoutData = controlsLayoutData;
 
var playPauseButton:PlayPauseToggleButton = new PlayPauseToggleButton();
controls.addChild(playPauseButton);
 
var seekBar:SeekSlider = new SeekSlider();
seekBar.layoutData = new HorizontalLayoutData(100, 100);
controls.addChild(seekBar);
 
var muteButton:MuteToggleButton = new MuteToggleButton();
controls.addChild(muteButton);
 
var fullScreenButton:FullScreenToggleButton = new FullScreenToggleButton();
controls.addChild(fullScreenButton);
 
player.addChild(controls);
 
var view:ImageLoader = new ImageLoader();
var viewLayoutData:AnchorLayoutData = new AnchorLayoutData(0, 0, 0, 0);
viewLayoutData.bottomAnchorDisplayObject = controls;
view.layoutData = viewLayoutData;
player.addChild(view);
 
player.width = 3 * this.stage.stageWidth / 4;
this.addChild(player);
 
player.addEventListener(Event.READY, function(event:Event):void
{
	view.source = player.texture;
});
 
player.pseudoStreaming = true;
player.start = 200;
player.videoSource = "http://www.site.com/video.mp4";
```

**Comment by zenrobin** [comment]
@joshtynjala  - thanks so much! 

Any chance the value is in milliseconds or frames?  I suspect it's in seconds, but want to be sure. 
Excited to give it a try either way :)

**Comment by pol2095** [comment]
The approximate time value, in seconds, to move to in a video file. [Help Adobe](http://help.adobe.com/fr_FR/FlashPlatform/reference/actionscript/3/flash/net/NetStream.html#seek())

**Comment by pol2095** [comment]
I made changes following your advice

**Pull request closed without merging**
